apiVersion: apps/v1
kind: Deployment
metadata:
  name: baby-botto
  namespace: discord-bots
  labels:
    app.kubernetes.io/name: MottoBotto
    app.kubernetes.io/instance: BabyBotto
    app.kubernetes.io/version: ${MOTTOBOTTO_VERSION}
  annotations:
    operator.1password.io/item-path: "vaults/du4s3tc4ab7wnrijmb5fxjpbse/items/BabyBotto Credentials"
    operator.1password.io/item-name: "babybotto-credentials"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: MottoBotto
      app.kubernetes.io/instance: BabyBotto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: MottoBotto
        app.kubernetes.io/instance: BabyBotto
        app.kubernetes.io/version: ${MOTTOBOTTO_VERSION}
    spec:
      containers:
      - name: bot
        image: ghcr.io/lovely-development-team/${IMAGE_NAME}:latest
        envFrom:
          - configMapRef:
              name: baby-botto
          - secretRef:
              name: babybotto-credentials
        env:
          - name: MOTTOBOTTO_VERSION
            value: ${MOTTOBOTTO_VERSION}
          - name: LOG_TO_FILE
            value: "false"
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
          limits:
            cpu: 30m
            memory: 100Mi